do
    local manager = getScriptManager()
    local editItem = function(item,k,v)
        local _item = manager:getItem(item)
        if _item ~= nil then
            _item:DoParam(k.."="..v)
        end
    end

    -- Magazines
    editItem("Base.FishingMag1","Icon","magazine_Fish_01")
    editItem("Base.FishingMag2","Icon","magazine_Fish_02")
    editItem("Base.ElectronicsMag1","Icon","magazine_Electric_01")
    editItem("Base.ElectronicsMag2","Icon","magazine_Electric_02")
    editItem("Base.ElectronicsMag3","Icon","magazine_Electric_03")
    editItem("Base.ElectronicsMag5","Icon","magazine_Electric_04") -- not a mistake, the player thinks this is 4
    editItem("Base.EngineerMagazine1","Icon","magazine_Engineer_01")
    editItem("Base.EngineerMagazine2","Icon","magazine_Engineer_02")
    editItem("Base.CookingMag1","Icon","magazine_Cook_01")
    editItem("Base.CookingMag2","Icon","magazine_Cook_02")
    editItem("Base.DairyCookingMag","Icon","magazine_Cook_03")
    editItem("Radio.RadioMag1","Icon","magazine_Radio_01")
    editItem("Radio.RadioMag2","Icon","magazine_Radio_02")
    editItem("Radio.RadioMag3","Icon","magazine_Radio_03")
    editItem("Base.HuntingMag1","Icon","magazine_Hunt_01")
    editItem("Base.HuntingMag2","Icon","magazine_Hunt_02")
    editItem("Base.HuntingMag3","Icon","magazine_Hunt_03")
    editItem("Base.MetalworkMag1","Icon","magazine_Metal_01")
    editItem("Base.MetalworkMag2","Icon","magazine_Metal_02")
    editItem("Base.MetalworkMag3","Icon","magazine_Metal_03")
    editItem("Base.MetalworkMag4","Icon","magazine_Metal_04")
    editItem("Base.SmithingMag1","Icon","magazine_Smith_01")
    editItem("Base.SmithingMag2","Icon","magazine_Smith_02")
    editItem("Base.SmithingMag3","Icon","magazine_Smith_03")
    editItem("Base.SmithingMag4","Icon","magazine_Smith_04")
    editItem("Base.FarmingMag1","Icon","magazine_Guide_01")
    editItem("Base.HerbalistMag","Icon","magazine_Guide_02")
    editItem("Base.ElectronicsMag4","Icon","magazine_Guide_03")
    editItem("Base.NutritionistMag","Icon","magazine_Guide_04")
    editItem("Base.MechanicMag1","Icon","magazine_Mechanic_01")
    editItem("Base.MechanicMag2","Icon","magazine_Mechanic_02")
    editItem("Base.MechanicMag3","Icon","magazine_Mechanic_03")
    editItem("Base.Journal","Icon","journalBlue")

    -- Books (chocolate)
    editItem("Base.BookCarpentry1","Icon","book_chocolate_Carpentry1")
    editItem("Base.BookCarpentry2","Icon","book_chocolate_Carpentry2")
    editItem("Base.BookCarpentry3","Icon","book_chocolate_Carpentry3")
    editItem("Base.BookCarpentry4","Icon","book_chocolate_Carpentry4")
    editItem("Base.BookCarpentry5","Icon","book_chocolate_Carpentry5")
    editItem("Base.BookCooking1","Icon","book_chocolate_Cooking1")
    editItem("Base.BookCooking2","Icon","book_chocolate_Cooking2")
    editItem("Base.BookCooking3","Icon","book_chocolate_Cooking3")
    editItem("Base.BookCooking4","Icon","book_chocolate_Cooking4")
    editItem("Base.BookCooking5","Icon","book_chocolate_Cooking5")
    editItem("Base.BookElectrician1","Icon","book_chocolate_Electrician1")
    editItem("Base.BookElectrician2","Icon","book_chocolate_Electrician2")
    editItem("Base.BookElectrician3","Icon","book_chocolate_Electrician3")
    editItem("Base.BookElectrician4","Icon","book_chocolate_Electrician4")
    editItem("Base.BookElectrician5","Icon","book_chocolate_Electrician4")
    editItem("Base.BookFarming1","Icon","book_chocolate_Farming1")
    editItem("Base.BookFarming2","Icon","book_chocolate_Farming2")
    editItem("Base.BookFarming3","Icon","book_chocolate_Farming3")
    editItem("Base.BookFarming4","Icon","book_chocolate_Farming4")
    editItem("Base.BookFarming5","Icon","book_chocolate_Farming5")
    editItem("Base.BookFishing1","Icon","book_chocolate_Fishing1")
    editItem("Base.BookFishing2","Icon","book_chocolate_Fishing2")
    editItem("Base.BookFishing3","Icon","book_chocolate_Fishing3")
    editItem("Base.BookFishing4","Icon","book_chocolate_Fishing4")
    editItem("Base.BookFishing5","Icon","book_chocolate_Fishing5")
    editItem("Base.BookFirstAid1","Icon","book_chocolate_FirstAid1")
    editItem("Base.BookFirstAid2","Icon","book_chocolate_FirstAid2")
    editItem("Base.BookFirstAid3","Icon","book_chocolate_FirstAid3")
    editItem("Base.BookFirstAid4","Icon","book_chocolate_FirstAid4")
    editItem("Base.BookFirstAid5","Icon","book_chocolate_FirstAid5")
    editItem("Base.BookForaging1","Icon","book_chocolate_Foraging1")
    editItem("Base.BookForaging2","Icon","book_chocolate_Foraging2")
    editItem("Base.BookForaging3","Icon","book_chocolate_Foraging3")
    editItem("Base.BookForaging4","Icon","book_chocolate_Foraging4")
    editItem("Base.BookForaging5","Icon","book_chocolate_Foraging5")
    editItem("Base.BookMechanic1","Icon","book_chocolate_Mechanic1")
    editItem("Base.BookMechanic2","Icon","book_chocolate_Mechanic2")
    editItem("Base.BookMechanic3","Icon","book_chocolate_Mechanic3")
    editItem("Base.BookMechanic4","Icon","book_chocolate_Mechanic4")
    editItem("Base.BookMechanic5","Icon","book_chocolate_Mechanic5")
    editItem("Base.BookMetalWelding1","Icon","book_chocolate_MetalWelding1")
    editItem("Base.BookMetalWelding2","Icon","book_chocolate_MetalWelding2")
    editItem("Base.BookMetalWelding3","Icon","book_chocolate_MetalWelding3")
    editItem("Base.BookMetalWelding4","Icon","book_chocolate_MetalWelding4")
    editItem("Base.BookMetalWelding5","Icon","book_chocolate_MetalWelding5")
    editItem("Base.BookBlacksmith1","Icon","book_chocolate_Blacksmith1")
    editItem("Base.BookBlacksmith2","Icon","book_chocolate_Blacksmith2")
    editItem("Base.BookBlacksmith3","Icon","book_chocolate_Blacksmith3")
    editItem("Base.BookBlacksmith4","Icon","book_chocolate_Blacksmith4")
    editItem("Base.BookBlacksmith5","Icon","book_chocolate_Blacksmith5")
    editItem("Base.BookTailoring1","Icon","book_chocolate_Tailoring1")
    editItem("Base.BookTailoring2","Icon","book_chocolate_Tailoring2")
    editItem("Base.BookTailoring3","Icon","book_chocolate_Tailoring3")
    editItem("Base.BookTailoring4","Icon","book_chocolate_Tailoring4")
    editItem("Base.BookTailoring5","Icon","book_chocolate_Tailoring5")
    editItem("Base.BookTrapping1","Icon","book_chocolate_Trapping1")
    editItem("Base.BookTrapping2","Icon","book_chocolate_Trapping2")
    editItem("Base.BookTrapping3","Icon","book_chocolate_Trapping3")
    editItem("Base.BookTrapping4","Icon","book_chocolate_Trapping4")
    editItem("Base.BookTrapping5","Icon","book_chocolate_Trapping5")

    --Better Sorting Compatibility
    if getActivatedMods():contains("BetterSortCC") then
        require("ItemTweaker_Copy_CC");
        editItem("IntReading.BookReading1","DisplayCategory","LitS");
        editItem("IntReading.BookReading2","DisplayCategory","LitS");
        editItem("IntReading.BookReading3","DisplayCategory","LitS");
        editItem("IntReading.BookReading4","DisplayCategory","LitS");
        editItem("IntReading.BookReading5","DisplayCategory","LitS");
        editItem("IntReading.BookReading6","DisplayCategory","LitS");
        editItem("IntReading.BookFantasy1","DisplayCategory","LitE");
        editItem("IntReading.BookFantasy2","DisplayCategory","LitE");
        editItem("IntReading.BookFantasy3","DisplayCategory","LitE");
        editItem("IntReading.BookStrength1","DisplayCategory","LitS");
        editItem("IntReading.BookStrength2","DisplayCategory","LitS");
        editItem("IntReading.BookStrength3","DisplayCategory","LitS");
        editItem("IntReading.BookStrength4","DisplayCategory","LitS");
        editItem("IntReading.BookStrength5","DisplayCategory","LitS");
        editItem("IntReading.BookStrength6","DisplayCategory","LitS");
        editItem("IntReading.BookFitness1","DisplayCategory","LitS");
        editItem("IntReading.BookFitness2","DisplayCategory","LitS");
        editItem("IntReading.BookFitness3","DisplayCategory","LitS");
        editItem("IntReading.BookFitness4","DisplayCategory","LitS");
        editItem("IntReading.BookFitness5","DisplayCategory","LitS");
        editItem("IntReading.BookFitness6","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot1","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot2","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot3","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot4","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot5","DisplayCategory","LitS");
        editItem("IntReading.BookLightfoot6","DisplayCategory","LitS");
        editItem("IntReading.BookNimble1","DisplayCategory","LitS");
        editItem("IntReading.BookNimble2","DisplayCategory","LitS");
        editItem("IntReading.BookNimble3","DisplayCategory","LitS");
        editItem("IntReading.BookNimble4","DisplayCategory","LitS");
        editItem("IntReading.BookNimble5","DisplayCategory","LitS");
        editItem("IntReading.BookNimble6","DisplayCategory","LitS");
        editItem("IntReading.BookSneak1","DisplayCategory","LitS");
        editItem("IntReading.BookSneak2","DisplayCategory","LitS");
        editItem("IntReading.BookSneak3","DisplayCategory","LitS");
        editItem("IntReading.BookSneak4","DisplayCategory","LitS");
        editItem("IntReading.BookSneak5","DisplayCategory","LitS");
        editItem("IntReading.BookSneak6","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting1","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting2","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting3","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting4","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting5","DisplayCategory","LitS");
        editItem("IntReading.BookSprinting6","DisplayCategory","LitS");
        editItem("IntReading.BookAiming1","DisplayCategory","LitS");
        editItem("IntReading.BookAiming2","DisplayCategory","LitS");
        editItem("IntReading.BookAiming3","DisplayCategory","LitS");
        editItem("IntReading.BookAiming4","DisplayCategory","LitS");
        editItem("IntReading.BookAiming5","DisplayCategory","LitS");
        editItem("IntReading.BookAiming6","DisplayCategory","LitS");
        editItem("IntReading.BookReloading1","DisplayCategory","LitS");
        editItem("IntReading.BookReloading2","DisplayCategory","LitS");
        editItem("IntReading.BookReloading3","DisplayCategory","LitS");
        editItem("IntReading.BookReloading4","DisplayCategory","LitS");
        editItem("IntReading.BookReloading5","DisplayCategory","LitS");
        editItem("IntReading.BookReloading6","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance1","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance2","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance3","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance4","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance5","DisplayCategory","LitS");
        editItem("IntReading.BookMaintenance6","DisplayCategory","LitS");
        editItem("IntReading.BookAxe1","DisplayCategory","LitS");
        editItem("IntReading.BookAxe2","DisplayCategory","LitS");
        editItem("IntReading.BookAxe3","DisplayCategory","LitS");
        editItem("IntReading.BookAxe4","DisplayCategory","LitS");
        editItem("IntReading.BookAxe5","DisplayCategory","LitS");
        editItem("IntReading.BookAxe6","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt1","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt2","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt3","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt4","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt5","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlunt6","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt1","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt2","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt3","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt4","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt5","DisplayCategory","LitS");
        editItem("IntReading.BookBlunt6","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade1","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade2","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade3","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade4","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade5","DisplayCategory","LitS");
        editItem("IntReading.BookSmallBlade6","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade1","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade2","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade3","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade4","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade5","DisplayCategory","LitS");
        editItem("IntReading.BookLongBlade6","DisplayCategory","LitS");
        editItem("IntReading.BookSpear1","DisplayCategory","LitS");
        editItem("IntReading.BookSpear2","DisplayCategory","LitS");
        editItem("IntReading.BookSpear3","DisplayCategory","LitS");
        editItem("IntReading.BookSpear4","DisplayCategory","LitS");
        editItem("IntReading.BookSpear5","DisplayCategory","LitS");
        editItem("IntReading.BookSpear6","DisplayCategory","LitS")
        editItem("IntReading.BookTrapping6","DisplayCategory","LitS")
        editItem("IntReading.BookFishing6","DisplayCategory","LitS")
        editItem("IntReading.BookCarpentry6","DisplayCategory","LitS")
        editItem("IntReading.BookFirstAid6","DisplayCategory","LitS")
        editItem("IntReading.BookBlacksmith6","DisplayCategory","LitS")
        editItem("IntReading.BookMetalWelding6","DisplayCategory","LitS")
        editItem("IntReading.BookElectrician6","DisplayCategory","LitS")
        editItem("IntReading.BookCooking6","DisplayCategory","LitS")
        editItem("IntReading.BookFarming6","DisplayCategory","LitS")
        editItem("IntReading.BookForaging6","DisplayCategory","LitS")
        editItem("IntReading.BookTailoring6","DisplayCategory","LitS")
    end
    
end
